name: Deploy Supabase Functions
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # This adds the manual "Run" button

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CLI
        uses: supabase/setup-cli@v1

      - name: Deploy Webhook
        run: |
          supabase functions deploy checkout-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
